--[[

============== Lore of entire game ==============
The entire world has been hit by a MASSIVE flood and there are only some islands that survived. The player has landed on 
these series of these islands but his family is on a different one.
Fortunately there was a small village at this fleet of islands and there was a sailer that was willing to help him out. 
However, he needed to get paid 6.7T dollars to help the player.
The player now has to search the fleet of islands for exotic animals to sell to an old man and earn his way back. 
save me

Strom lore:
Strom was also stranded on this island together with this small amount of inhabitants. 
However, he was asleep when the flood hit and he forgot to take his mechanical arm with him.
He really misses his wife Stroma and can't sail back to the main island because he doesn't have arms to hold the oars. 
He asks the player to complete quests in order to help strom forge back a mechanical arm.
Strom repays him with money.

]]