local RarityLabels = {}

RarityLabels.ImageIds = {
	Common = '112845288559546',
	Uncommon = '85666286276627',
	Rare = '75500604168240',
	Epic = '74979376583227',
	Legendary = '76985621108307',
	Mythic = '80598210407931',
	Exotic = '108803904490827',
	Limited = '112845288559546', -- didnt make limited one
}

RarityLabels.Animals = {}

-- ============= All Rarities =============== --
RarityLabels.Animals.Common = {}

RarityLabels.Animals.Uncommon = {}

RarityLabels.Animals.Rare = {}

RarityLabels.Animals.Epic = {}

RarityLabels.Animals.Legendary = {}

RarityLabels.Animals.Mythic = {}

RarityLabels.Animals.Exotic = {}

RarityLabels.Animals.Limited = {}

-- =============== Assigning Animals ============== --
RarityLabels.Animals.Common = {
	'Chicken',
	'Monkey'
}


RarityLabels.Animals.Uncommon = {
	'Pig',
	'Gorilla'
}


RarityLabels.Animals.Rare = {
	'Cow',
	'Frog'
}


RarityLabels.Animals.Epic = {
	'Dog',
	'MudSkipper',
	'Anaconda'
}


RarityLabels.Animals.Legendary = {
	'Panda',
}

RarityLabels.Animals.Exotic = {
	'Phoenix'
}

return RarityLabels
