local Rarities = {}

Rarities.GrassLands = {
	['Chicken'] = {
		Rarity = 2,
	},
	
	['Pig'] = {
		Rarity = 8,
	},
	
	['Cow'] = {
		Rarity = 32,
	},
	
	['Dog'] = {
		Rarity = 128,
	},
	
	['Phoenix'] = {
		Rarity = 16384,
	},
}

Rarities.Jungle = {
	['Monkey'] = {
		Rarity = 2
	},
	
	['Gorilla'] = {
		Rarity = 10
	},
	
	['Frog'] = {
		Rarity = 35
	},
	
	['MudSkipper'] = {
		Rarity = 100
	},
	
	['Anaconda'] = {
		Rarity = 150
	},
	
	['Panda'] = {
		Rarity = 1200
	},
}

Rarities.Icelands = {
	
}

return Rarities
