local XPGiven = {}

XPGiven.Xp = {
	['Chicken'] = {
		BaseXp = 10
	},

	['Pig'] = {
		BaseXp = 20
	},

	['Cow'] = {
		BaseXp = 50
	},

	['Dog'] = {
		BaseXp = 500,
	},

	['Phoenix'] = {
		BaseXp = 15000,
	},
	
	['Monkey'] = {
		BaseXp = 25
	},
	
	['Gorilla'] = {
		BaseXp = 45
	},
	
	['Frog'] = {
		BaseXp = 100
	},
	
	['MudSkipper'] = {
		BaseXp = 575
	},
	
	['Anaconda'] = {
		BaseXp = 800
	},
	
	['Panda'] = {
		BaseXp = 3400
	},
}

return XPGiven 